# Generated by Django 3.2.6 on 2021-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.CharField(choices=[('Amusement Park', 'Amusement Park'), ('Hiking', 'Hiking'), ('Sight-seeing', 'Sight-seeing'), ('Restaurant', 'Restaurant')], max_length=200, null=True),
        ),
    ]
