# Generated by Django 3.2.6 on 2021-10-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(choices=[('Brooklyn', 'Brooklyn'), ('New York City', 'New York City'), ('Queens', 'Queens'), ('Bronx', 'Bronx'), ('Staten Island', 'Staten Island')], max_length=200, null=True),
        ),
    ]
